"""
main.py
=======
This is the actual "web server" piece - the part that makes you
accessible by URL. Run it with:

    uvicorn main:app --reload

Then visit http://localhost:8000/docs to see (and test!) your API
live, auto-generated by FastAPI from the type hints below. This is
the FastAPI feature I mentioned: you get this for free, no extra work.

How a request flows through this file:
  1. Browser sends POST /chat with {"text": "...", "user_id": "..."}
  2. We look up THIS user's settings/reminders/notes from the DB
     (not a global - see database.py)
  3. We call understand_command() from brain.py to classify intent
  4. Based on intent, we call the matching brain.py function
  5. We return {"reply": "..."} as JSON
  6. The BROWSER speaks the reply out loud (Web Speech API) - Python
     never touches audio at all.
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
import datetime

import brain
import database

app = FastAPI(title="Sky Assistant API")

# CORS: allows your frontend (possibly on a different domain) to call
# this API from the browser. Locked down to "*" for development -
# tighten this to your real frontend domain before going to production.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

database.init_db()


# ── Request/response shapes. FastAPI uses these for validation AND
#    for the auto-generated docs at /docs ──

class ChatRequest(BaseModel):
    text: str
    user_id: str


class ChatResponse(BaseModel):
    reply: str
    intent: str


@app.get("/")
def health_check():
    return {"status": "Sky is awake", "docs": "/docs"}


@app.post("/chat", response_model=ChatResponse)
def chat(req: ChatRequest):
    settings = database.get_settings(req.user_id)
    understood = brain.understand_command(req.text)
    intent = understood.get("intent", "unknown")

    reply = route_intent(intent, understood, req.text, req.user_id, settings)

    return ChatResponse(reply=reply, intent=intent)


def route_intent(intent, understood, raw_text, user_id, settings):
    """
    Same dispatch logic as your original run_assistant() loop's
    if/elif chain - just returning strings instead of calling speak().
    """
    user_name = settings.get("user_name", "Boss")
    ai_name = settings.get("ai_name", "Sky")

    if intent == "greeting":
        return f"Hello {user_name}! How can I help you?"

    elif intent == "how_are_you":
        return f"I am doing great {user_name}, thank you for asking!"

    elif intent == "name":
        return f"My name is {ai_name}, your personal AI voice assistant!"

    elif intent == "time_and_date":
        return brain.get_time_and_date()

    elif intent == "time":
        return brain.get_time()

    elif intent == "date":
        return brain.get_date()

    elif intent == "reminder_set":
        task = understood.get("task")
        time_str = understood.get("time")
        if not task or not time_str:
            return "Tell me what to remind you about and at what time, e.g. 'remind me to call mum at 5 pm'."
        database.add_reminder(user_id, task, time_str)
        return f"Done! I will remind you to {task} at {time_str}."

    elif intent == "reminder_show":
        reminders = database.get_reminders(user_id)
        if not reminders:
            return "You have no reminders set!"
        parts = [f"{r['task']} at {r['time']}" for r in reminders]
        return f"You have {len(reminders)} reminder(s): " + "; ".join(parts)

    elif intent == "timer":
        # NOTE: a real countdown timer now belongs in the BROWSER
        # (setTimeout in JS), not the server - the server shouldn't
        # hold a connection open for 10 minutes per user. We just
        # confirm here; frontend handles the actual countdown.
        duration = understood.get("duration") or "the requested time"
        return f"Okay, starting a timer for {duration}. (handled in your browser)"

    elif intent == "note_take":
        text = understood.get("task") or raw_text
        database.add_note(user_id, text)
        return f"Got it! I have noted: {text}"

    elif intent == "note_show":
        notes = database.get_notes(user_id)
        if not notes:
            return "You have no notes saved yet!"
        latest = notes[-1]
        return f"You have {len(notes)} note(s). Latest: {latest['text']}"

    elif intent == "calculate":
        expr = understood.get("expression") or raw_text
        return brain.calculate(expr)

    elif intent == "weather":
        city = understood.get("city") or settings.get("default_city")
        return brain.get_weather(city, settings.get("default_city", "Thrissur"))

    elif intent == "ask":
        return brain.answer_question(understood.get("topic") or raw_text)

    elif intent == "joke":
        return brain.get_joke()

    elif intent == "small_talk":
        return understood.get("reply") or "That is interesting! Tell me more."

    else:
        return brain.answer_question(raw_text)


# ── Settings endpoints (replace the old "change" intent / customize()) ──

class SettingsUpdate(BaseModel):
    user_id: str
    ai_name: str | None = None
    user_name: str | None = None
    default_city: str | None = None


@app.get("/settings/{user_id}")
def read_settings(user_id: str):
    return database.get_settings(user_id)


@app.post("/settings")
def update_settings(body: SettingsUpdate):
    settings = database.get_settings(body.user_id)
    if body.ai_name:
        settings["ai_name"] = body.ai_name
    if body.user_name:
        settings["user_name"] = body.user_name
    if body.default_city:
        settings["default_city"] = body.default_city
    database.save_settings(body.user_id, settings)
    return settings


# Serve the frontend (index.html, etc) directly from FastAPI so the
# WHOLE app - frontend + backend - is one URL. Simplest possible
# deployment for a demo / personal project.
app.mount("/", StaticFiles(directory="../frontend", html=True), name="frontend")
